Mi tarea 2
lbenet/2022-2_TSFC2 pull request #20
Opened 2022-05-04 04:42 UTC by SealPi

Se me fue subir mi tarea, realmente no la he terminado, tengo problemas con la potencia 1/2 y las trigonométricas. Me parece que al usar `coefs= Float64[ ]` no es la mejor forma de ir creando mi arreglo.

2022-05-04 15:29 UTC, lbenet commented
No he revisado tu tarea, por lo que debes tomar el siguiente comentario como un comentario [de lo que escribiste](https://github.com/lbenet/2022-2_TSFC2/pull/20#issue-1224917203): `coefs= Float64[ ]` es sólo útil para el caso `Taylor{Float64}`, pero no lo es para otros casos, por ejemplo, `Taylor{BigFloat}`. 

Una vez dicho lo anterior, e insisto que no he visto tu código, un posible tip: si escribes una función de la forma `function ff(x::Taylor{T}) where {T}`, entonces, dentro de la función puedes escribir `coefs = T[]`, lo que declara al vector `coefs`, cuyos elementos son del tipo `T`, que imagino es lo que quieres hacer. Si conoces el número de elementos, entonces puedes escribir `coefs = Vector{T}(undef, n)`. La diferencia entre ambas opciones es que, en la primera, tienes que ir añadiendo los elementos de forma ordenada con `push!`, mientras que en la segunda puedes escribir cosas de la forma `coefs[i] = ...`, lo que sobreescribe el campo `i` de `coefs`.

2022-05-09 17:07 UTC, lbenet requested changes
Primero que nada, perdón por la demora, ha sido una semana muy pesada... 

Ya le eché un primer vistazo a tu tarea. Es difícil checar la tarea con los tests, ya que no metiste todo tu código en un módulo (llamado `SeriesTaylor`). Por esto, mi primer sugerencia es que hagas esto para que la parte "sencilla" de checar los tests la podamos llevar a cabo. Haciendo los tests a pata, los dos primeros bloques de tests pasan sin problemas! En cuanto al tercero, hay 7 tests que fallan (fail) y 13 que dan un error. Los tests que fallan, es decir, que calculan otra cosa, están relacionados con las funciones `sqrt`, `log`,  `sin`, `cos`. Faltan además otras funciones aún.

Dejé varios comentarios, algunos son tips de estilo o alternativas de programación, o mejoras respecto a escribir código en julia.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +     return Taylor(coefs)
El código que tienes es correcto. Sin embargo, otra manera de escribir estas líneas es:
```julia
    coef = zeros(a, orden+1)
    coef[2] = one(a)
    return Taylor(coef)
```
Las ventajas del código que incluí son que no cambias el tamaño del vector, sólo tienes un vector (no dos), y `one(a)` te evita la conversión de `1` (`Int`) al tipo definido por `a`, que ocurre aunque no la ves.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> + Taylor(a=Int64) = Taylor(Float64,a)
Esta línea seguramente la debes escribir como:
```julia
Taylor(a::Int64) = Taylor(Float64,a)
```
De la manera en que la escribiste, `a` tiene como valor de default el tipo `Int64`, y no impone que sea un entero. (Además, el tener esta línea te puede llevar a otros errores, como al usar `Taylor(8.3)`...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs=type[]
Quizás lo que buscas aquí es tener sólo el tipo. Entonces, puedes usar `promote_type(typeof(a.coefs[1]), typeof(b.coefs[1]))`. Una alternativa distinta es que calcules el coeficiente cero (a.coefs[1]*b.coefs[1]) y que uses el tipo del resultado para definir  `coefs`.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +        sum=0
Sugiero escribir aquí `sum = zero(type)`, lo que evita la estabilidad de tipo asociada a convertir `sum`, que inicialmente es `Int`, al tipo `type`.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs=type[]
Otra observación: el tamaño de `coefs` lo conoces: es i+1

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +function ^(a::Taylor, b::Float64)
En el caso de esta función, sugiero separar los casos en que `b` es `Int`, u otra cosa. Y si esa otra cosa satisface `b == Int(b)` (por ejemplo, 1.0) entonces usas el método específico con `b::Int`.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +     if b==2
La idea de separar casos específicos (b==0, b==1, b==2, b==-1) es buena. Mi recomendación, para `b==2` es que dentro del `if` llames a otra función (`sqr`, `cuadrado`, o el nombre que quieras) donde implementas el caso optimizado.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs= Float64[a.coefs[1]^2]   ## coefs[1]= a.coefs^2
Igual que sugerí arriba, el tipo de `coefs` lo puedes encontrar a partir del coeficiente de orden cero, que es simplemente `a.coefs[1]^2`. En lo que escribiste impones que el tipo sea `Float64`...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +               sum=0
Mismo comentario sobre la inestabilidad de tipo asociada a esta línea...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +               if mod(k,2)==0
También puedes utilizar `iseven(k)`, lo que te evite hacer el cálculo `mod(k,2)`...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +                    for j in 0:(k-3)/2
Por qué el ciclo de `j` termina en `(k-3)/2`, y no en `(k-1)/2`? (Checa las notas del curso.)

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    elseif b==1/2
Este caso particular lo puedes poner en la función `sqrt`. La ventaja de ponerlo en `sqrt`, en lugar que desde `sqrt` llegues aquí, es la facilidad que representa mantener el código en `sqrt` (una función "pequeña") respecto a `^`, que es una función más complicada...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    #@assert a.coefs[1] > 0
Me parece que este `@assert` es correcto, o al menos algo parecido es necesario. Por un lado, el primer término es `sqrt(a.coefs[1])`, y por otro lado, `a.coefs[1]` aparece en el denominador de los siguientes coeficientes.

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs= Float64[exp(a.coefs[1])]
Nuevamente, el tipo que requieres está en `exp(a.coefs[1])`, por lo que no requieres *convertir* a `Float64`; piensa en el caso en que `a` es del tipo `Taylor{BigFloat}`, por ejemplo...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +            sum=0
Mismo comentario sobre la inestabilidad de tipo...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs= Float64[exp(a.coefs[1])]
Nota que `i` te da el tamaño de `coefs`...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +function log(a::Taylor{<:ComplexF64})
Mismos comentarios que arriba: `i` te da el tamaño de `coefs`, `log(a.coefs[1])` te da el tipo de `coefs`, y `sum=0` induce una estabilidad de tipo...

2022-05-09 17:07 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +function sin(a::Taylor)
La función `sin(a::Taylor)` y la función `cos(a::Taylor)` están relacionadas entre sí; checa las notas del curso. Te conviene definir una función en que se calculen ambas, y que `sin(a)` corresponda a la parte del seno, y `cos(a)` únicamente a la del coseno. Yo creo que aquí están los errores relacionados a la ejecución de estas funciones.

Y aquí también se aplican comentarios que te he dejado antes.

2022-05-18 05:42 UTC, SealPi commented
Buenas noches, lamento mucho mi demora.

La verdad aún tengo fallas con la potencia, por ende con la raíz. eso me lleva a tener un problema con asin. Y bueno cómo definimos acos. Yo creo ya mejor le voy a meter nitro a la otra tarea. Saludos!

2022-05-18 13:51 UTC, lbenet reviewed
Te dejé varios comentarios. Los problemas que hay están surgiendo porque conviertes a `Taylor{Complex64}` en casos en que eso no es necesario. Si quieres lidiar con los casos complejos debes entonces evitar usar comparaciones (ej., `a.coefs[1] < 0`) ya que ésas no tienen sentido con complejos.

Sugiero que trates de correr los tests por tu cuenta y trates de corregir siguiendo los comentarios las funciones `^` (y `sqrt`) y después `log`.

Falta poco...

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
>  function ^(a::Taylor, b::Float64)
Recomiendo lo siguiente:
- Tener dos métodos distintos para `^`:  uno que se aplique cuando la potencia es `Int` (`^(a::Taylor, n::Int)`) y el otro para *otros casos* (`^(a::Taylor{T}, b::T) where {T<:AbstractFloat}`). Ciertamente va a haber redundancia, en el sentido de que `a^3` y `a^3.0` deben dar lo mismo; esos lo puedes checar a través de `if`s adecuados. Para los "otros casos" cuando `n::Int`, yo haría que este usara el método con "AbstractFloats", con `return a^float(n)`, por ejemplo.
- Hay varios casos específicos "fáciles", `a^0`, `a^1`, `a^2`, que los debes tratar con `if`s. Para `a^2` sugiero que escribas una función especializada: `n == 2 && return cuadrado(a)`, donde `cuadrado(a)` usa el método optimizado.
- En el "método genérico" (con `AbstractFloat`s también debes incluir los casos especiales: `iszero(n)`, `n==1`, `n==2`, `n==0.5 && return sqrt(a)`, etc, y ahí incluyes el código general.

Todo esto hará que el código sea más específico y fácil de detectar en cuanto a los problemas.

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs[1]= a.coefs[1]^2
Conviene escribir esto de la siguiente manera:
```julia
aux = a.coefs[1]^b
coefs= zeros(typeof(aux), i)
coefs[1] = aux
```
Nota que usas la `b` tal cual (que puede ser `2`, `2.0` o `BigFloat(2.0)`) para que haga la promoción correcta.

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
>  function ^(a::Taylor, b::Float64)
Vale la pena decir que si sigues este esquema debes ser cuidadoso en cuestiones de estabilidad de tipo.

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +        return a^(1/2)
Este tipo de casos los debes separar en métodos, y no con un `if` que involucre el tipo: eso es parte de la importancia de "multiple dispatch" en julia. Entonces, esto lo debes escribir:
```julia
function sqrt(a::Taylor{T}) where {T<:Complex}
```
Nota que hay más tipos `Complex` que `Complex64`...

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
>      elseif b==1/2
Yo escribiría esta parte del código en la función `sqrt`...

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs[1]= sqrt(a.coefs[1])
Mismo comentario que arriba...

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    type= typeof(sqrt(Complex(a.coefs[1])))
Es incorrecto que pases a que tus coeficientes sean complejos (si tienes inicialmente coeficientes de punto flotante no complejos) según el signo del coeficiente. Eso hace que tu código no sea estable respecto al tipo. En este caso es mejor lanzar un error.

Tu código sirve para ilustrar la inestabilidad de tipo:
```julia
julia> t = Taylor(5)
Taylor{Float64}([0.0, 1.0, 0.0, 0.0, 0.0, 0.0])

# El resultado siguiente es correcto, y del tipo Taylor{Float64} (ok!)
julia> sqrt(1.0+t) 
Taylor{Float64}([1.0, 0.5, -0.125, 0.0625, -0.0390625, 0.02734375])

# El resultado siguiente es incorrecto, y es del tipo Taylor{Complex64}
julia> sqrt(1.0-t)  
Taylor{ComplexF64}(ComplexF64[0.0 + 1.0im, 0.0 - 0.5im, 0.0 - 0.125im, 0.0 - 0.0625im, 0.0 - 0.0390625im, 0.0 - 0.02734375im])
```
Los coeficientes que calculas son correctos, pero **no** deben ser complejos ni imaginarios; son reales!

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
>  function ^(a::Taylor, b::Float64)
Por cierto, vale la pena tener los casos específicos "antes" y el código genérico "después"

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs[1]= log(Complex(a.coefs[1]))
Mismo comentario sobre cambiar el tipo según el valor (o signo) de los coeficientes. Si checas los tests, se espera que si evalúas `log(-2+t)` te de un `AssertionError`. Esto lo generas sencillamente con `@assert a.coefs[1] >= 0`...

Si quieres generar el caso para `Taylor{Complex{T}}`, eso lo debes hacer por separado (otro método) y en ese caso (coeficientes complejos) no tiene sentido la comparación `a.coefs[1] >= 0`, así que tu código debería funcionar.

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    coefs[1]= log(Complex(a.coefs[1]))
Igual que antes, insisto (línea 270) no cambies de tipo a coeficientes complejos. Si lo haces *pierdes* la posibilidad de usar las relaciones de orden (`<`, `>`, ...).
```julia
# El siguiente resultado es correcto
julia> log(1 + t)
Taylor{Float64}([0.0, 1.0, -0.5, 0.3333333333333333, -0.25, 0.2])

# El siguiente resultado NO es correcto
julia> log(1 - t)
Taylor{ComplexF64}(ComplexF64[0.0 + 3.141592653589793im, -1.0 + 0.0im, -0.5 + 0.0im, -0.3333333333333333 + 0.0im, -0.25 + 0.0im, -0.2 + 0.0im])
```
El único cambio en las dos expresiones (partiendo de la correcta) es `t->-t`, por lo que el signo de los coeficientes impares debe cambiar, sin que cambie la magnitud.

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +    type2= typeof(cos(a.coefs[1]))
Son del mismo tipo... así que con un `type` basta...

2022-05-18 13:51 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> +        R= sqrt(1-a^2)
El código es correcto, pero como en `sqrt` haces que esto se comporte como `Taylor{Complex64}` eso te genera los problemas...

2022-05-26 16:29 UTC, Julian-RC commented
Tal y como lo menciona Luis tienes problemas acerca para dividir los casos en tipos. Si bien el ```if``` puede solucionar las cosas en cuestión de estilo es mejor tomar diferentes funciones y por lo tanto métodos específicos para cada tipo.

Si bien esto puede ser de alguna algo lento, es mejor que se tengan claros casos específicos y después (solo si es posible) determina el caso general. Como bien lo ha dicho Luis lo primero es que funcione y después optimizar tanto a nivel código como procesamiento.

Por el tiempo que tienes puedes dejar lo que funciona como está pero trata de mejorar este tipo de cosas, enfocate en tu problema con los complejos para poder comenzar la próxima tarea lo antes posible.

2022-05-29 20:04 UTC, SealPi commented on tareas/Seal/series_taylor.jl
>  function ^(a::Taylor, b::Float64)
Me ayudaron mucho! sus hints

2022-05-29 20:06 UTC, SealPi commented
Gracias ! a ambos por la gran ayuda y en verdad me da mucha pena mi retardo en la entrega, según yo ya casi pasa todos los test; pero justo hay un part donde hay raíces de negativos.

2022-05-29 20:29 UTC, Julian-RC commented
Ok, Sealtiel ntp. Revisando tus errores me parece que el método acos se te esta pasano, tienes asin y atan pero creo que te olvidaste de acos.

2022-05-29 21:50 UTC, SealPi commented
Ya lo agregué pero aún tengo problemas, ninguna de esas funciones jala. de hecho también `sqrt(sqrt(2-t)) ` ya que 2-t tiene su primer entrada negativa.

2022-05-29 23:21 UTC, lbenet commented on tareas/Seal/series_taylor.jl
> + -(a::Taylor)= Taylor(-a.coefs)
El problema en el test de `sqrt` proviene de aquí! Si examinas el resultado de `1-t` con tu código, obtienes:
```julia
julia> t = Taylor(5)
Taylor{Float64}([0.0, 1.0, 0.0, 0.0, 0.0, 0.0])

julia> 1 - t
Taylor{Float64}([-1.0, 1.0, 0.0, 0.0, 0.0, 0.0])
```
El último resultado muestra que lo que hiciste es calcular `t-1` y no `1-t`...

2022-05-30 01:38 UTC, SealPi commented on tareas/Seal/series_taylor.jl
> + -(a::Taylor)= Taylor(-a.coefs)
\ö/ en definitiva era eso! GRACIAS!

2022-05-30 01:44 UTC, SealPi commented
Listo ahora  me parece que ya quedó!
Agradezco mucho la retroalimentación

2022-05-30 06:40 UTC, Julian-RC reviewed
Tu tarea solo falla en un test, por ahora con que cambies esto basta. Nota que mos estamos adecuando a los test. Ya te puedes concentrar en la tarea 3 ! solo este cambio y no habrá más problemas :)

2022-05-30 06:40 UTC, Julian-RC commented on tareas/Seal/series_taylor.jl
> +    if a.coefs[1] < 0
```suggestion
    @assert a.coefs[1] > 0
```
Un cambio

2022-05-30 06:40 UTC, Julian-RC commented on tareas/Seal/series_taylor.jl
> +    end
```suggestion

```
Esto no es necesario.

2022-05-30 12:15 UTC, SealPi commented on tareas/Seal/series_taylor.jl
> +    end
listo!

2022-05-30 13:34 UTC, Julian-RC commented
Perfecto! Tarea aceptada! Muy buen trabajo :)

2022-05-30 13:34 UTC, merged